version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./pharmashield.db
      - JWT_SECRET=pharmashield_jwt_docker_secret_2026
      - SAP_MODE=MOCK
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api
      - NEXT_PUBLIC_WS_BASE_URL=ws://localhost:8000/ws
    depends_on:
      - backend
